# This file tells Google Cloud Build how to build and deploy app.
# Final version: Uses 'docker:20.10' for compatibility and passes all build-time secrets.

steps:
  # 1. Get ALL build-time secrets from Secret Manager
  - name: 'google/cloud-sdk:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret=NIKE_STORE_DATABASE_URL > db_url.txt
        gcloud secrets versions access latest --secret=NIKE_STORE_BETTER_AUTH_SECRET > auth_secret.txt
    
  # 2. Build the Docker image
  # We use 'docker:20.10' to match the Cloud Build daemon API version
  - name: 'docker:20.10'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        docker build \
          --build-arg "DATABASE_URL=$(cat db_url.txt)" \
          --build-arg "BETTER_AUTH_SECRET=$(cat auth_secret.txt)" \
          -t "${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/nike-store-repo/nike-store:$SHORT_SHA" \
          .

  # 3. Push the image to Artifact Registry
  # We use 'docker:20.10' here as well for consistency
  - name: 'docker:20.10'
    args:
      - 'push'
      - '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/nike-store-repo/nike-store:$SHORT_SHA'

 # 4. Deploy the new image to Cloud Run
  - name: 'google/cloud-sdk:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy nike-store \
          --image "${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/nike-store-repo/nike-store:$SHORT_SHA" \
          --region "${_LOCATION}" \
          --allow-unauthenticated \
          --port=3000 \  # <-- ADD THIS LINE
          --service-account=nike-store-runtime@gen-lang-client-0866064925.iam.gserviceaccount.com \
          --update-env-vars=BETTER_AUTH_URL=http://localhost:3000,NODE_ENV=production \ # <-- REMOVED PORT=3000
          --update-secrets=DATABASE_URL=NIKE_STORE_DATABASE_URL:latest,BETTER_AUTH_SECRET=NIKE_STORE_BETTER_AUTH_SECRET:latest
          
# This stores the built image in Artifact Registry
images:
  - '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/nike-store-repo/nike-store:$SHORT_SHA'

# Set up some substitutions (we'll define these in the trigger)
substitutions:
  _LOCATION: 'us-central1' # Use the same location as your Artifact Registry

# This section is required by your org policy
options:
  logging: CLOUD_LOGGING_ONLY