# This file tells Google Cloud Build how to build and deploy app.
# This version uses public Docker Hub images to bypass org policies.

steps:
  # 1. Get the DATABASE_URL from Secret Manager to use as a build-arg
  # We use the official 'google/cloud-sdk' image from Docker Hub
  - name: 'google/cloud-sdk:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret=NIKE_STORE_DATABASE_URL > db_url.txt
    
  # 2. Build the Docker image
  # We use the official 'docker' image from Docker Hub
  - name: 'docker:latest'
    args:
      - 'build'
      - '--build-arg'
      - 'DATABASE_URL=$(cat db_url.txt)'
      - '-t'
      - '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/nike-store-repo/nike-store:$SHORT_SHA'
      - '.'

  # 3. Push the image to Artifact Registry
  # We use the official 'docker' image from Docker Hub
  - name: 'docker:latest'
    args:
      - 'push'
      - '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/nike-store-repo/nike-store:$SHORT_SHA'

  # 4. Deploy the new image to Cloud Run
  # We use the official 'google/cloud-sdk' image from Docker Hub
  - name: 'google/cloud-sdk:latest'
    args:
      - 'run'
      - 'deploy'
      - 'nike-store'
      - '--image'
      - '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/nike-store-repo/nike-store:$SHORT_SHA'
      - '--region'
      - '${_LOCATION}'
      - '--allow-unauthenticated'
      - '--service-account=nike-store-runtime@gen-lang-client-0866064925.iam.gserviceaccount.com'
      # Set runtime environment variables
      - '--update-env-vars=BETTER_AUTH_URL=http://localhost:3000,NODE_ENV=production,PORT=3000'
      # Set runtime secrets
      - '--update-secrets=DATABASE_URL=NIKE_STORE_DATABASE_URL:latest,BETTER_AUTH_SECRET=NIKE_STORE_BETTER_AUTH_SECRET:latest'

# This stores the built image in Artifact Registry
images:
  - '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/nike-store-repo/nike-store:$SHORT_SHA'

# Set up some substitutions (we'll define these in the trigger)
substitutions:
  _LOCATION: 'us-central1' # Use the same location as your Artifact Registry

# This section is required by your org policy
options:
  logging: CLOUD_LOGGING_ONLY